name: CI-CD

on:
  push:
    branches: 
      - "main"
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Docker Login
        uses: docker/build-push-action@v4.0.0
        witch:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            afsantos01/cigitlab:v1
            afsantos01/cigitlab:latest
