name: CI

on:
  push:
    branches: 
      - "main"
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.user }}
          password: ${{ secrets.passwd }}
      - name: Construção da imagem
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            afsantos01/cgitlab:${{github.run_number}}
            afsantos01/cgitlab:latest
CD:
  runs-on: ubuntu:latest
  needs: [CI]
  steps:
    - uses: actions/checkout@v3.3.0
    
    - name: Definindo o contexto
      uses: Azure/k8s-set-context@v3.0
      with:
        method: kubeconfig
        kubekonfig: ${{secrets.k8s_config}}
